### ISSUE TITLE
Joomla 4 produziert einen Fehler weil isSite nicht mehr unterstützt wird

### ISSUE THREAD

**Issue by RalfRoemling** [JoomTools/plg_content_jtgaoo#4]
`isSite` muß durch `isClient('Site')` ersetzt werden.

**Comment by degobbis** [comment]
Danke für den Hinweis.
Das Plugin ist ist jedoch obsolet, da laut DSGVO für alle Systeme ein Opt-In erforderlich ist.

Eine Weiterentwicklung ist also nicht angedacht.

Gruß Guido

**Comment by RalfRoemling** [comment]
Guter Punkt. Hatte mir das Plugin auf die Funktion gar nicht mehr angesehen.
